version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: test
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    networks:
      - blockhouse-network

  app:
    build: .
    container_name: blockhouse-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://myuser:test@postgres:5432/orders"
    networks:
      - blockhouse-network

networks:
  blockhouse-network:
    driver: bridge
